/**
 * Local photography, single-sourced.
 *
 * The files in `imgs/` are content-hashed, so they carry no semantic name.
 * Every slot below is therefore assigned by aspect ratio: the closest-fitting
 * photo crops least under `object-cover`. There are more slots than photos,
 * so a few repeat - if you drop more landscape shots into `imgs/`, re-run
 * `npm run imgs` and widen LANDSCAPE below.
 *
 * GENERATED by scripts/import-images.mjs - do not edit by hand.
 */

const p = (file: string) => `/images/${file}`;

/* Landscape 1.21-1.50 - banners, page heroes, wide gallery tiles. */
const LANDSCAPE = [
  p("fc066196685bd22013f39d81651b1d18.jpg"), // 736x490  1.50  WhatsApp Image 2026-09-26 at 10.35.42 (12).jpeg
  p("bbb2eba128d50379aa94fd88ad5b3b1f.jpg"), // 736x552  1.33  WhatsApp Image 2026-09-26 at 10.35.39 (2).jpeg
  p("ae12f2de1d2481fe87724738a74116ad.jpg"), // 736x552  1.33  WhatsApp Image 2026-09-26 at 10.35.39 (4).jpeg
  p("1b826d45429fc863155d96fdd0fe8206.jpg"), // 736x552  1.33  WhatsApp Image 2026-09-26 at 10.35.39.jpeg
];

/* Square 1.0 - standard gallery tiles and card-safe crops. */
const SQUARE = [
  p("93bbd604a1708a8ec647e4e1477e5cd3.jpg"), // 700x700  1.00  WhatsApp Image 2026-09-26 at 10.35.40 (5).jpeg
  p("eb63c0585fc92c84b9604a77ad832af9.jpg"), // 736x736  1.00  WhatsApp Image 2026-09-26 at 10.35.40 (7).jpeg
  p("6a2dc6d06bce4f14876a911d43d49547.jpg"), // 640x640  1.00  WhatsApp Image 2026-09-26 at 10.35.40.jpeg
  p("2d1a538abdbf505e629439ec1d153692.jpg"), // 736x736  1.00  WhatsApp Image 2026-09-26 at 10.35.41.jpeg
  p("3b03e9b74e8626386865781b1ade6d05.jpg"), // 736x736  1.00  WhatsApp Image 2026-09-26 at 10.35.42 (10).jpeg
  p("026de8f36b5a48ee200640422215613e.jpg"), // 736x736  1.00  WhatsApp Image 2026-09-26 at 10.35.42 (2).jpeg
];

/* Portrait 0.53-0.80 - products, variants, categories, tall tiles. */
const PORTRAIT = [
  p("722c409355ea1b257fcffac9ad74c45f.jpg"), // 736x920  0.80  WhatsApp Image 2026-09-26 at 10.35.42 (6).jpeg
  p("722594337cd0404894960da95bac0c85.jpg"), // 736x920  0.80  WhatsApp Image 2026-09-26 at 10.35.42 (8).jpeg
  p("6810cafab629f718fa1b3fcbecc73894.jpg"), // 736x920  0.80  WhatsApp Image 2026-09-26 at 10.35.43 (2).jpeg
  p("32f5312120115c193648b5d87b0c2d5e.jpg"), // 735x921  0.80  WhatsApp Image 2026-09-26 at 10.35.40 (3).jpeg
  p("8bbe890a02dc3d74a06923a90119d470.jpg"), // 736x981  0.75  WhatsApp Image 2026-09-26 at 10.35.39 (7).jpeg
  p("a3275c39eebc7f96ff8e4d0068396c2e.jpg"), // 736x981  0.75  WhatsApp Image 2026-09-26 at 10.35.40 (1).jpeg
  p("58cec0fa0b8e9419b71ee79748d02435.jpg"), // 736x981  0.75  WhatsApp Image 2026-09-26 at 10.35.40 (8).jpeg
  p("ca52cd588e9675652905324b50a76cdc.jpg"), // 736x981  0.75  WhatsApp Image 2026-09-26 at 10.35.41 (2).jpeg
  p("4bd99f974839ce2291700c66e7e125de.jpg"), // 736x981  0.75  WhatsApp Image 2026-09-26 at 10.35.41 (8).jpeg
  p("c1c71f63e869c9d3bc7205249624b5de.jpg"), // 736x981  0.75  WhatsApp Image 2026-09-26 at 10.35.42 (1).jpeg
  p("672050b54fa748ad09b0f0565c9843dd.jpg"), // 736x981  0.75  WhatsApp Image 2026-09-26 at 10.35.42 (15).jpeg
  p("a8ebd8bbc507432ad09e2ea2e6ae883f.jpg"), // 720x960  0.75  WhatsApp Image 2026-09-26 at 10.35.41 (7).jpeg
];

/** The Agati mark, served from public/images. */
export const LOGO = p("agati-logo.png");

/** Homepage. */
export const HERO = LANDSCAPE[0];
export const INTRO = PORTRAIT[0];
export const FEATURED = LANDSCAPE[1] ?? LANDSCAPE[0];
export const WORKSHOP = PORTRAIT[1] ?? PORTRAIT[0];
export const TIMBER_RACKS = SQUARE[0] ?? PORTRAIT[0];

/** One banner per page so no two pages open on the same photo. */
export const PAGE_HERO = {
  about: LANDSCAPE[0],
  furniture: LANDSCAPE[1] ?? LANDSCAPE[0],
  "custom-furniture": SQUARE[0] ?? LANDSCAPE[0],
  projects: SQUARE[1] ?? SQUARE[0],
  gallery: SQUARE[2] ?? SQUARE[1] ?? SQUARE[0],
  services: LANDSCAPE[0],
  contact: SQUARE[1] ?? SQUARE[0],
} as const;

/* data.ts - ordered to match the editorial arrays they feed. */
export const SERVICE_IMAGES = [
  LANDSCAPE[0],
  LANDSCAPE[1] ?? LANDSCAPE[0],
  SQUARE[0] ?? LANDSCAPE[0],
  SQUARE[1] ?? SQUARE[0],
  SQUARE[2] ?? SQUARE[1] ?? SQUARE[0],
  LANDSCAPE[0],
];

export const PROJECT_IMAGES = [
  SQUARE[0] ?? PORTRAIT[0],
  SQUARE[1] ?? SQUARE[0] ?? PORTRAIT[0],
  SQUARE[2] ?? SQUARE[1] ?? SQUARE[0],
  LANDSCAPE[1] ?? LANDSCAPE[0],
  LANDSCAPE[0],
  SQUARE[0] ?? PORTRAIT[0],
];

/** Workshop stills, also used as category fallbacks. */
export const GALLERY_IMAGES = [
  PORTRAIT[1] ?? PORTRAIT[0],
  SQUARE[0] ?? LANDSCAPE[0],
  SQUARE[1] ?? SQUARE[0] ?? LANDSCAPE[0],
  LANDSCAPE[0],
  SQUARE[2] ?? SQUARE[1] ?? SQUARE[0],
  PORTRAIT[0],
  LANDSCAPE[1] ?? LANDSCAPE[0],
  PORTRAIT[2] ?? PORTRAIT[0],
  PORTRAIT[3] ?? PORTRAIT[0],
  PORTRAIT[0],
];

/* db/seed.sql - mirrored there as literal paths. */
export const CATEGORY_IMAGES = [PORTRAIT[0], PORTRAIT[1] ?? PORTRAIT[0], PORTRAIT[4] ?? PORTRAIT[0]];

/** 19 rows, one per product_images entry, in seed order. */
export const PRODUCT_IMAGES = Array.from({ length: 19 }, (_, i) => PORTRAIT[i % PORTRAIT.length]);

/**
 * 13 rows, one per product_variants entry. A colourway reuses its own
 * product's front photo rather than an unrelated one, so the detail view
 * never shows a variant that contradicts the product beside it.
 */
export const VARIANT_IMAGES = [
  PRODUCT_IMAGES[0],
  PRODUCT_IMAGES[0],
  PRODUCT_IMAGES[0],
  PRODUCT_IMAGES[3],
  PRODUCT_IMAGES[3],
  PRODUCT_IMAGES[7],
  PRODUCT_IMAGES[7],
  PRODUCT_IMAGES[7],
  PRODUCT_IMAGES[12],
  PRODUCT_IMAGES[12],
  PRODUCT_IMAGES[12],
  PRODUCT_IMAGES[17],
  PRODUCT_IMAGES[17],
];
